version: "3"

services:

  manual:
    image: ${REGISTRY_URL}/sphinx-manual
    volumes:
    - ${SPHINX_DOC}:/opt/sphinx/doc/
    networks:
      default:
      hub_net:
        aliases: 
        - ${HUB_INSTANCE}
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"